### ISSUE TITLE
Setup Capston Kanban

### ISSUE THREAD

**Issue by abdozayan12** [rubydevi/catalogue-of-my-things#29]
Link to project: https://github.com/rubydevi/catalogue-of-my-things/projects/1

- There are four members of this team

- @rubydevi  is team member 1
- @abdozayan12 is team member 2
- @Yonashenok  is team member 3
 - @H-Ramalan is team member 4

**Comment by TedLivist** [comment]
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @abdozayan12, @Yonashenok, @rubydevi and @H-Ramalan,

Good job so far!
✔️ Kanban columns are complete
✔️ Tasks are well-assigned
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Kindly ensure all your tasks have descriptions. This task does not have a description.

   ![image](https://github.com/rubydevi/catalogue-of-my-things/assets/36542986/c80f1831-021f-45c9-ba06-a7752271612a)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Olamarx** [comment]
Hi Team,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media0.giphy.com/media/1O1UUSESiuGSi1VdT6/giphy.gif"/>
## Highlights
- Changes fixed ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
